area: base
webserver_port: 3000
port_base: 30000
node_red_ip: 127.0.0.1
node_red_port: 1880
ports:
  port_in_from_input_node_base: 33000
  port_out_to_node_red_base: 34000
  port_node_red_in_base: 35000
  port_node_red_out_base: 36000
  port_in_from_node_red_base: 37000
  port_out_to_proxy_or_output_node_base: 38000
  port_output_node_in_base: 29000
  port_range_limit: 50
areas:
  - name: area1
    proxy_ip: 192.168.0.100
    proxy_port_base: 30000
    proxy_webserver_port: 3000
    node_red_ip: 192.168.0.100
    node_red_port: 1880
  - name: area2
    proxy_ip: 192.168.0.101
    proxy_port_base: 30000
    proxy_webserver_port: 3000
    node_red_ip: 192.168.0.101
    node_red_port: 1880
  - name: area3
    proxy_ip: 192.168.0.102
    proxy_port_base: 30000
    proxy_webserver_port: 3000
    node_red_ip: 192.168.0.102
    node_red_port: 1880
input_nodes:
  - name: input_node0.1
    area: base
    flow: Flow Area 0.1
    ip: 192.168.0.104
    port: 21001
  - name: input_node0.2
    area: base
    flow: Flow Area 0.2
    ip: 192.168.0.104
    port: 21002
  - name: input_node0.3
    area: base
    flow: Flow Area 0.3
    ip: 192.168.0.104
    port: 21003
  - name: input_node1.1
    area: area1
    flow: Flow Area 1.1
    ip: 192.168.0.100
    port: 21001
  - name: input_node1.2
    area: area1
    flow: Flow Area 1.2
    ip: 192.168.0.100
    port: 21002
  - name: input_node1.3
    area: area1
    flow: Flow Area 1.3
    ip: 192.168.0.100
    port: 21003
  - name: input_node2.1
    area: area2
    flow: Flow Area 2.1
    ip: 192.168.0.101
    port: 21001
  - name: input_node2.2
    area: area2
    flow: Flow Area 2.2
    ip: 192.168.0.101
    port: 21002
  - name: input_node2.3
    area: area2
    flow: Flow Area 2.3
    ip: 192.168.0.101
    port: 21003
  - name: input_node3.1
    area: area3
    flow: Flow Area 3.1
    ip: 192.168.0.102
    port: 21001
  - name: input_node3.2
    area: area3
    flow: Flow Area 3.2
    ip: 192.168.0.102
    port: 21002
  - name: input_node3.3
input_nodes:
  - name: output_node0.1
    area: base
    flow: Flow Area 0.1
    ip: 192.168.0.104
    port: 29001
  - name: output_node0.2
    area: base
    flow: Flow Area 0.2
    ip: 192.168.0.104
    port: 29002
  - name: output_node0.3
    area: base
    flow: Flow Area 0.3
    ip: 192.168.0.104
    port: 29003
  - name: output_node1.1
    area: area1
    flow: Flow Area 1.1
    ip: 192.168.0.100
    port: 29001
  - name: output_node1.2
    area: area1
    flow: Flow Area 1.2
    ip: 192.168.0.100
    port: 29002
  - name: output_node1.3
    area: area1
    flow: Flow Area 1.3
    ip: 192.168.0.100
    port: 29003
  - name: output_node2.1
    area: area2
    flow: Flow Area 2.1
    ip: 192.168.0.101
    port: 29001
  - name: output_node2.2
    area: area2
    flow: Flow Area 2.2
    ip: 192.168.0.101
    port: 29002
  - name: output_node2.3
    area: area2
    flow: Flow Area 2.3
    ip: 192.168.0.101
    port: 29003
  - name: output_node3.1
    area: area3
    flow: Flow Area 3.1
    ip: 192.168.0.102
    port: 29001
  - name: output_node3.2
    area: area3
    flow: Flow Area 3.2
    ip: 192.168.0.102
    port: 29002
  - name: output_node3.3
    area: area3
    flow: Flow Area 3.3
    ip: 192.168.0.102
    port: 29003

